# Notebook 06: Silver-to-Gold Aggregations

## Objective

This notebook transforms the validated PaySim Silver dataset into business-ready
Gold tables.

The Gold layer will provide:

- daily transaction summaries;
- hourly fraud-monitoring summaries;
- transaction-type summaries;
- origin-account activity summaries;
- destination-account activity summaries;
- high-value transaction summaries;
- fraud-monitoring datasets;
- an analytics-ready fraud feature table.

The Gold layer is designed for reporting, SQL analytics, dashboards, and
downstream machine-learning consumers.

Balance columns are retained in Silver but excluded from the fraud feature table
because the dataset documentation warns that they may introduce target leakage.

In [1]:
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
)
from pyspark.sql.window import Window

In [2]:
os.environ["PYSPARK_PYTHON"] = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable
os.environ["SPARK_LOCAL_IP"] = "127.0.0.1"

print("Python executable:", sys.executable)

Python executable: c:\Projects\paysim-financial-data-pipeline\.venv\Scripts\python.exe

In [3]:
spark = (
    SparkSession.builder
    .appName("PaySimSilverToGold")
    .master("local[4]")
    .config("spark.driver.memory", "8g")
    .config("spark.sql.shuffle.partitions", "64")
    .config("spark.sql.session.timeZone", "UTC")
    .config("spark.driver.host", "127.0.0.1")
    .config("spark.driver.bindAddress", "127.0.0.1")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

print("Spark version:", spark.version)
print("Driver memory:", spark.conf.get("spark.driver.memory"))
print(
    "Shuffle partitions:",
    spark.conf.get("spark.sql.shuffle.partitions"),
)

c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\testing\utils.py:127: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

Spark version: 4.2.0
Driver memory: 8g
Shuffle partitions: 64

In [4]:
PROJECT_ROOT = Path(
    r"C:\Projects\paysim-financial-data-pipeline"
)

RAW_DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "PS_20174392719_1491204439457_log.csv"
)

GOLD_SUMMARY_OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "gold"
    / "summary_exports"
)

AUDIT_OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "gold"
    / "pipeline_audit"
)

GOLD_SUMMARY_OUTPUT_PATH.mkdir(
    parents=True,
    exist_ok=True,
)

AUDIT_OUTPUT_PATH.mkdir(
    parents=True,
    exist_ok=True,
)

print("Raw source:", RAW_DATA_PATH)
print("Source exists:", RAW_DATA_PATH.exists())

Raw source: C:\Projects\paysim-financial-data-pipeline\data\raw\PS_20174392719_1491204439457_log.csv
Source exists: True

In [5]:
if not RAW_DATA_PATH.exists():
    raise FileNotFoundError(
        f"Source file not found: {RAW_DATA_PATH}"
    )

In [6]:
transaction_schema = StructType(
    [
        StructField("step", IntegerType(), nullable=True),
        StructField("type", StringType(), nullable=True),
        StructField("amount", DoubleType(), nullable=True),
        StructField("nameOrig", StringType(), nullable=True),
        StructField("oldbalanceOrg", DoubleType(), nullable=True),
        StructField("newbalanceOrig", DoubleType(), nullable=True),
        StructField("nameDest", StringType(), nullable=True),
        StructField("oldbalanceDest", DoubleType(), nullable=True),
        StructField("newbalanceDest", DoubleType(), nullable=True),
        StructField("isFraud", IntegerType(), nullable=True),
        StructField("isFlaggedFraud", IntegerType(), nullable=True),
    ]
)

In [7]:
pipeline_run_id = str(uuid.uuid4())

pipeline_start_timestamp = datetime.now(
    timezone.utc
)

source_filename = RAW_DATA_PATH.name

print("Pipeline run ID:", pipeline_run_id)
print("Pipeline start:", pipeline_start_timestamp)

Pipeline run ID: 8be59cd7-9b19-4889-81c3-7adc20adbd19
Pipeline start: 2026-07-25 23:56:41.365225+00:00

In [8]:
raw_df = (
    spark.read
    .option("header", "true")
    .option("sep", ",")
    .option("encoding", "UTF-8")
    .option("mode", "PERMISSIVE")
    .schema(transaction_schema)
    .csv(str(RAW_DATA_PATH))
)

In [9]:
SOURCE_COLUMNS = [
    "step",
    "type",
    "amount",
    "nameOrig",
    "oldbalanceOrg",
    "newbalanceOrig",
    "nameDest",
    "oldbalanceDest",
    "newbalanceDest",
    "isFraud",
    "isFlaggedFraud",
]

In [10]:
record_hash_expression = F.sha2(
    F.concat_ws(
        "||",
        *[
            F.coalesce(
                F.col(column).cast("string"),
                F.lit("<NULL>"),
            )
            for column in SOURCE_COLUMNS
        ],
    ),
    256,
)

In [11]:
bronze_df = (
    raw_df
    .withColumn(
        "_pipeline_run_id",
        F.lit(pipeline_run_id),
    )
    .withColumn(
        "_ingestion_timestamp",
        F.current_timestamp(),
    )
    .withColumn(
        "_ingestion_date",
        F.to_date(F.current_timestamp()),
    )
    .withColumn(
        "_source_file",
        F.lit(source_filename),
    )
    .withColumn(
        "_source_file_path",
        F.lit(str(RAW_DATA_PATH)),
    )
    .withColumn(
        "_record_hash",
        record_hash_expression,
    )
)

In [12]:
standardized_df = (
    bronze_df
    .withColumnRenamed(
        "type",
        "transaction_type",
    )
    .withColumnRenamed(
        "nameOrig",
        "origin_account",
    )
    .withColumnRenamed(
        "oldbalanceOrg",
        "old_balance_origin",
    )
    .withColumnRenamed(
        "newbalanceOrig",
        "new_balance_origin",
    )
    .withColumnRenamed(
        "nameDest",
        "destination_account",
    )
    .withColumnRenamed(
        "oldbalanceDest",
        "old_balance_destination",
    )
    .withColumnRenamed(
        "newbalanceDest",
        "new_balance_destination",
    )
    .withColumnRenamed(
        "isFraud",
        "is_fraud",
    )
    .withColumnRenamed(
        "isFlaggedFraud",
        "is_flagged_fraud",
    )
    .withColumn(
        "transaction_type",
        F.upper(F.trim(F.col("transaction_type"))),
    )
    .withColumn(
        "origin_account",
        F.trim(F.col("origin_account")),
    )
    .withColumn(
        "destination_account",
        F.trim(F.col("destination_account")),
    )
)

In [13]:
HIGH_VALUE_THRESHOLD = 200_000.0

silver_enriched_df = (
    standardized_df
    .withColumn(
        "transaction_day",
        F.ceil(
            F.col("step") / F.lit(24)
        ).cast("integer"),
    )
    .withColumn(
        "hour_of_day",
        (
            (F.col("step") - F.lit(1))
            % F.lit(24)
        ).cast("integer"),
    )
    .withColumn(
        "destination_category",
        F.when(
            F.col("destination_account").startswith("M"),
            F.lit("MERCHANT"),
        )
        .when(
            F.col("destination_account").startswith("C"),
            F.lit("CUSTOMER"),
        )
        .otherwise(
            F.lit("UNKNOWN"),
        ),
    )
    .withColumn(
        "is_customer_destination",
        (
            F.col("destination_category")
            == F.lit("CUSTOMER")
        ).cast("integer"),
    )
    .withColumn(
        "is_merchant_destination",
        (
            F.col("destination_category")
            == F.lit("MERCHANT")
        ).cast("integer"),
    )
    .withColumn(
        "is_high_value_transaction",
        (
            F.col("amount")
            > F.lit(HIGH_VALUE_THRESHOLD)
        ).cast("integer"),
    )
    .withColumn(
        "is_zero_amount",
        (
            F.col("amount") == 0
        ).cast("integer"),
    )
    .withColumn(
        "is_self_transfer",
        (
            F.col("origin_account")
            == F.col("destination_account")
        ).cast("integer"),
    )
    .withColumn(
        "amount_category",
        F.when(
            F.col("amount") == 0,
            F.lit("ZERO"),
        )
        .when(
            F.col("amount") < 1_000,
            F.lit("LOW"),
        )
        .when(
            F.col("amount") < 50_000,
            F.lit("MEDIUM"),
        )
        .when(
            F.col("amount") <= 200_000,
            F.lit("HIGH"),
        )
        .otherwise(
            F.lit("VERY_HIGH"),
        ),
    )
)

In [14]:
VALID_TRANSACTION_TYPES = [
    "CASH_IN",
    "CASH_OUT",
    "DEBIT",
    "PAYMENT",
    "TRANSFER",
]

In [15]:
validated_df = (
    silver_enriched_df
    .withColumn(
        "fail_missing_critical_field",
        (
            F.col("step").isNull()
            | F.col("transaction_type").isNull()
            | F.col("amount").isNull()
            | F.col("origin_account").isNull()
            | F.col("destination_account").isNull()
            | F.col("is_fraud").isNull()
            | F.col("is_flagged_fraud").isNull()
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_transaction_type",
        (
            ~F.col("transaction_type").isin(
                VALID_TRANSACTION_TYPES
            )
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_step",
        (
            ~F.col("step").between(1, 744)
        ).cast("integer"),
    )
    .withColumn(
        "fail_negative_amount",
        (
            F.col("amount") < 0
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_fraud_flag",
        (
            ~F.col("is_fraud").isin(0, 1)
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_flagged_fraud",
        (
            ~F.col("is_flagged_fraud").isin(0, 1)
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_origin_account",
        (
            ~F.col("origin_account").rlike(
                r"^C[0-9]+$"
            )
        ).cast("integer"),
    )
    .withColumn(
        "fail_invalid_destination_account",
        (
            ~F.col("destination_account").rlike(
                r"^[CM][0-9]+$"
            )
        ).cast("integer"),
    )
)

In [16]:
hard_failure_columns = [
    "fail_missing_critical_field",
    "fail_invalid_transaction_type",
    "fail_invalid_step",
    "fail_negative_amount",
    "fail_invalid_fraud_flag",
    "fail_invalid_flagged_fraud",
    "fail_invalid_origin_account",
    "fail_invalid_destination_account",
]

In [17]:
validated_df = validated_df.withColumn(
    "hard_failure_count",
    sum(
        F.col(column)
        for column in hard_failure_columns
    ),
)

In [18]:
silver_final_df = (
    validated_df
    .filter(
        F.col("hard_failure_count") == 0
    )
)

In [19]:
silver_record_count = silver_final_df.count()

print(
    "Silver record count:",
    f"{silver_record_count:,}",
)

Silver record count: 6,362,620

In [20]:
silver_final_df.show(n=10)

+----+----------------+--------+--------------+------------------+------------------+-------------------+-----------------------+-----------------------+--------+----------------+--------------------+--------------------+---------------+--------------------+--------------------+--------------------+---------------+-----------+--------------------+-----------------------+-----------------------+-------------------------+--------------+----------------+---------------+---------------------------+-----------------------------+-----------------+--------------------+-----------------------+--------------------------+---------------------------+--------------------------------+------------------+
|step|transaction_type|  amount|origin_account|old_balance_origin|new_balance_origin|destination_account|old_balance_destination|new_balance_destination|is_fraud|is_flagged_fraud|    _pipeline_run_id|_ingestion_timestamp|_ingestion_date|        _source_file|   _source_file_path|        _record_hash|transaction_day|hour_of_day|destination_category|is_customer_destination|is_merchant_destination|is_high_value_transaction|is_zero_amount|is_self_transfer|amount_category|fail_missing_critical_field|fail_invalid_transaction_type|fail_invalid_step|fail_negative_amount|fail_invalid_fraud_flag|fail_invalid_flagged_fraud|fail_invalid_origin_account|fail_invalid_destination_account|hard_failure_count|
+----+----------------+--------+--------------+------------------+------------------+-------------------+-----------------------+-----------------------+--------+----------------+--------------------+--------------------+---------------+--------------------+--------------------+--------------------+---------------+-----------+--------------------+-----------------------+-----------------------+-------------------------+--------------+----------------+---------------+---------------------------+-----------------------------+-----------------+--------------------+-----------------------+--------------------------+---------------------------+--------------------------------+------------------+
|   1|         PAYMENT| 9839.64|   C1231006815|          170136.0|         160296.36|        M1979787155|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|43363620118f0498b...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT| 1864.28|   C1666544295|           21249.0|          19384.72|        M2044282225|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|54d2627165384f4e5...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|        TRANSFER|   181.0|   C1305486145|             181.0|               0.0|         C553264065|                    0.0|                    0.0|       1|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|05b5efb9f4bdb7fb2...|              1|          0|            CUSTOMER|                      1|                      0|                        0|             0|               0|            LOW|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|        CASH_OUT|   181.0|    C840083671|             181.0|               0.0|          C38997010|                21182.0|                    0.0|       1|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|bd0a1524a32e53ba0...|              1|          0|            CUSTOMER|                      1|                      0|                        0|             0|               0|            LOW|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT|11668.14|   C2048537720|           41554.0|          29885.86|        M1230701703|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|aaef92d030d19d787...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT| 7817.71|     C90045638|           53860.0|          46042.29|         M573487274|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|09752485ee671ac58...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT| 7107.77|    C154988899|          183195.0|         176087.23|         M408069119|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|32ba69770ac1ebb6a...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT| 7861.64|   C1912850431|         176087.23|         168225.59|         M633326333|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|11f00359e1b5799e5...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|         PAYMENT| 4024.36|   C1265012928|            2671.0|               0.0|        M1176932104|                    0.0|                    0.0|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|2bdf013e7720caf62...|              1|          0|            MERCHANT|                      0|                      1|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
|   1|           DEBIT| 5337.77|    C712410124|           41720.0|          36382.23|         C195600860|                41898.0|               40348.79|       0|               0|8be59cd7-9b19-488...|2026-07-25 23:56:...|     2026-07-25|PS_20174392719_14...|C:\Projects\paysi...|1739518584a9c7add...|              1|          0|            CUSTOMER|                      1|                      0|                        0|             0|               0|         MEDIUM|                          0|                            0|                0|                   0|                      0|                         0|                          0|                               0|                 0|
+----+----------------+--------+--------------+------------------+------------------+-------------------+-----------------------+-----------------------+--------+----------------+--------------------+--------------------+---------------+--------------------+--------------------+--------------------+---------------+-----------+--------------------+-----------------------+-----------------------+-------------------------+--------------+----------------+---------------+---------------------------+-----------------------------+-----------------+--------------------+-----------------------+--------------------------+---------------------------+--------------------------------+------------------+
only showing top 10 rows

In [21]:
silver_final_df.cache()

DataFrame[step: int, transaction_type: string, amount: double, origin_account: string, old_balance_origin: double, new_balance_origin: double, destination_account: string, old_balance_destination: double, new_balance_destination: double, is_fraud: int, is_flagged_fraud: int, _pipeline_run_id: string, _ingestion_timestamp: timestamp, _ingestion_date: date, _source_file: string, _source_file_path: string, _record_hash: string, transaction_day: int, hour_of_day: int, destination_category: string, is_customer_destination: int, is_merchant_destination: int, is_high_value_transaction: int, is_zero_amount: int, is_self_transfer: int, amount_category: string, fail_missing_critical_field: int, fail_invalid_transaction_type: int, fail_invalid_step: int, fail_negative_amount: int, fail_invalid_fraud_flag: int, fail_invalid_flagged_fraud: int, fail_invalid_origin_account: int, fail_invalid_destination_account: int, hard_failure_count: int]

In [22]:
silver_record_count = silver_final_df.count()

print(
    "Cached Silver records:",
    f"{silver_record_count:,}",
)

Cached Silver records: 6,362,620

In [23]:
gold_daily_transaction_summary_df = (
    silver_final_df
    .groupBy(
        "transaction_day",
    )
    .agg(
        F.count("*").alias(
            "transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "total_transaction_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "average_transaction_amount"
        ),
        F.round(
            F.min("amount"),
            2,
        ).alias(
            "minimum_transaction_amount"
        ),
        F.round(
            F.max("amount"),
            2,
        ).alias(
            "maximum_transaction_amount"
        ),
        F.sum("is_fraud").alias(
            "fraud_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_count"
        ),
        F.sum(
            "is_high_value_transaction"
        ).alias(
            "high_value_transaction_count"
        ),
        F.countDistinct(
            "origin_account"
        ).alias(
            "unique_origin_accounts"
        ),
        F.countDistinct(
            "destination_account"
        ).alias(
            "unique_destination_accounts"
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.round(
            F.col("fraud_count")
            / F.col("transaction_count")
            * F.lit(100),
            6,
        ),
    )
    .withColumn(
        "fraud_amount_pct",
        F.round(
            F.col("fraud_amount")
            / F.col("total_transaction_amount")
            * F.lit(100),
            6,
        ),
    )
    .orderBy(
        "transaction_day"
    )
)
gold_daily_transaction_summary_df.show(
    n=10,
    truncate=False,
)

+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+----------------------+---------------------------+--------------+----------------+
|transaction_day|transaction_count|total_transaction_amount|average_transaction_amount|minimum_transaction_amount|maximum_transaction_amount|fraud_count|fraud_amount  |flagged_fraud_count|high_value_transaction_count|unique_origin_accounts|unique_destination_accounts|fraud_rate_pct|fraud_amount_pct|
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+----------------------+---------------------------+--------------+----------------+
|1              |574255           |9.213186562565E10       |160437.2                  |0.1                       |1.0E7                     |271        |2.1116382746E8|0                  |155750                      |574184                |249521                     |0.047192      |0.229197        |
|2              |455238           |7.123864239716E10       |156486.59                 |0.14                      |1.0E7                     |309        |3.7923968507E8|0                  |123855                      |455188                |240371                     |0.067877      |0.532351        |
|3              |1070             |4.4708447263E8          |417835.96                 |1.66                      |1.0E7                     |310        |3.945088606E8 |0                  |301                         |1070                  |1069                       |28.971963     |88.24034        |
|4              |28240            |3.83054736059E9         |135642.61                 |0.24                      |1.0E7                     |262        |4.3824681602E8|0                  |5355                        |28240                 |27196                      |0.927762      |11.440841       |
|5              |9789             |1.32513383905E9         |135369.68                 |0.68                      |1.0E7                     |252        |2.4498057812E8|0                  |1817                        |9789                  |9674                       |2.574318      |18.487233       |
|6              |441005           |7.340998636834E10       |166460.67                 |0.21                      |1.0E7                     |228        |3.672335824E8 |0                  |125465                      |440962                |263701                     |0.0517        |0.50025         |
|7              |420583           |6.707077758477E10       |159470.97                 |0.06                      |1.0E7                     |272        |4.017901288E8 |0                  |114931                      |420548                |278057                     |0.064672      |0.599054        |
|8              |449637           |7.003059850048E10       |155749.19                 |0.02                      |1.0E7                     |278        |3.5199401701E8|0                  |118684                      |449589                |311072                     |0.061828      |0.502629        |
|9              |417919           |5.806776539842E10       |138945.02                 |0.0                       |1.0E7                     |255        |3.8457125476E8|1                  |98229                       |417883                |311081                     |0.061017      |0.66228         |
|10             |392945           |6.519035217702E10       |165901.98                 |0.02                      |1.0E7                     |282        |3.7306069837E8|0                  |105648                      |392909                |302912                     |0.071766      |0.572264        |
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+----------------------+---------------------------+--------------+----------------+
only showing top 10 rows

In [24]:
gold_daily_basic_summary_df = (
    silver_final_df
    .groupBy("transaction_day")
    .agg(
        F.count("*").alias("transaction_count"),

        F.round(
            F.sum("amount"),
            2,
        ).alias("total_transaction_amount"),

        F.round(
            F.avg("amount"),
            2,
        ).alias("average_transaction_amount"),

        F.round(
            F.min("amount"),
            2,
        ).alias("minimum_transaction_amount"),

        F.round(
            F.max("amount"),
            2,
        ).alias("maximum_transaction_amount"),

        F.sum("is_fraud").alias("fraud_count"),

        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(F.lit(0.0))
            ),
            2,
        ).alias("fraud_amount"),

        F.sum("is_flagged_fraud").alias(
            "flagged_fraud_count"
        ),

        F.sum("is_high_value_transaction").alias(
            "high_value_transaction_count"
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.when(
            F.col("transaction_count") > 0,
            F.round(
                F.col("fraud_count")
                / F.col("transaction_count")
                * F.lit(100.0),
                6,
            ),
        ).otherwise(F.lit(0.0)),
    )
    .withColumn(
        "fraud_amount_pct",
        F.when(
            F.col("total_transaction_amount") > 0,
            F.round(
                F.col("fraud_amount")
                / F.col("total_transaction_amount")
                * F.lit(100.0),
                6,
            ),
        ).otherwise(F.lit(0.0)),
    )
    .orderBy("transaction_day")
)

gold_daily_basic_summary_df.show(
    n=10,
    truncate=False,
)

+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+
|transaction_day|transaction_count|total_transaction_amount|average_transaction_amount|minimum_transaction_amount|maximum_transaction_amount|fraud_count|fraud_amount  |flagged_fraud_count|high_value_transaction_count|fraud_rate_pct|fraud_amount_pct|
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+
|1              |574255           |9.213186562565E10       |160437.2                  |0.1                       |1.0E7                     |271        |2.1116382746E8|0                  |155750                      |0.047192      |0.229197        |
|2              |455238           |7.123864239716E10       |156486.59                 |0.14                      |1.0E7                     |309        |3.7923968507E8|0                  |123855                      |0.067877      |0.532351        |
|3              |1070             |4.4708447263E8          |417835.96                 |1.66                      |1.0E7                     |310        |3.945088606E8 |0                  |301                         |28.971963     |88.24034        |
|4              |28240            |3.83054736059E9         |135642.61                 |0.24                      |1.0E7                     |262        |4.3824681602E8|0                  |5355                        |0.927762      |11.440841       |
|5              |9789             |1.32513383905E9         |135369.68                 |0.68                      |1.0E7                     |252        |2.4498057812E8|0                  |1817                        |2.574318      |18.487233       |
|6              |441005           |7.340998636834E10       |166460.67                 |0.21                      |1.0E7                     |228        |3.672335824E8 |0                  |125465                      |0.0517        |0.50025         |
|7              |420583           |6.707077758477E10       |159470.97                 |0.06                      |1.0E7                     |272        |4.017901288E8 |0                  |114931                      |0.064672      |0.599054        |
|8              |449637           |7.003059850048E10       |155749.19                 |0.02                      |1.0E7                     |278        |3.5199401701E8|0                  |118684                      |0.061828      |0.502629        |
|9              |417919           |5.806776539842E10       |138945.02                 |0.0                       |1.0E7                     |255        |3.8457125476E8|1                  |98229                       |0.061017      |0.66228         |
|10             |392945           |6.519035217702E10       |165901.98                 |0.02                      |1.0E7                     |282        |3.7306069837E8|0                  |105648                      |0.071766      |0.572264        |
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+
only showing top 10 rows

In [25]:
gold_daily_account_counts_df = (
    silver_final_df
    .groupBy("transaction_day")
    .agg(
        F.approx_count_distinct(
            "origin_account",
            rsd=0.02,
        ).alias("estimated_unique_origin_accounts"),

        F.approx_count_distinct(
            "destination_account",
            rsd=0.02,
        ).alias("estimated_unique_destination_accounts"),
    )
)

In [26]:
gold_daily_account_counts_df.show(
    n=10,
    truncate=False,
)

+---------------+--------------------------------+-------------------------------------+
|transaction_day|estimated_unique_origin_accounts|estimated_unique_destination_accounts|
+---------------+--------------------------------+-------------------------------------+
|7              |419640                          |277622                               |
|5              |10006                           |10029                                |
|2              |454264                          |237577                               |
|1              |564366                          |247776                               |
|3              |1068                            |1065                                 |
|6              |432541                          |258228                               |
|4              |28226                           |27765                                |
|11             |401981                          |323727                               |
|8              |441790                          |305162                               |
|10             |393689                          |300173                               |
+---------------+--------------------------------+-------------------------------------+
only showing top 10 rows

In [27]:
gold_daily_transaction_summary_df = (
    gold_daily_basic_summary_df
    .join(
        gold_daily_account_counts_df,
        on="transaction_day",
        how="left",
    )
    .orderBy("transaction_day")
)

In [28]:
gold_daily_transaction_summary_df.show(
    n=10,
    truncate=False,
)

+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+--------------------------------+-------------------------------------+
|transaction_day|transaction_count|total_transaction_amount|average_transaction_amount|minimum_transaction_amount|maximum_transaction_amount|fraud_count|fraud_amount  |flagged_fraud_count|high_value_transaction_count|fraud_rate_pct|fraud_amount_pct|estimated_unique_origin_accounts|estimated_unique_destination_accounts|
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+--------------------------------+-------------------------------------+
|1              |574255           |9.213186562565E10       |160437.2                  |0.1                       |1.0E7                     |271        |2.1116382746E8|0                  |155750                      |0.047192      |0.229197        |564366                          |247776                               |
|2              |455238           |7.123864239716E10       |156486.59                 |0.14                      |1.0E7                     |309        |3.7923968507E8|0                  |123855                      |0.067877      |0.532351        |454264                          |237577                               |
|3              |1070             |4.4708447263E8          |417835.96                 |1.66                      |1.0E7                     |310        |3.945088606E8 |0                  |301                         |28.971963     |88.24034        |1068                            |1065                                 |
|4              |28240            |3.83054736059E9         |135642.61                 |0.24                      |1.0E7                     |262        |4.3824681602E8|0                  |5355                        |0.927762      |11.440841       |28226                           |27765                                |
|5              |9789             |1.32513383905E9         |135369.68                 |0.68                      |1.0E7                     |252        |2.4498057812E8|0                  |1817                        |2.574318      |18.487233       |10006                           |10029                                |
|6              |441005           |7.340998636834E10       |166460.67                 |0.21                      |1.0E7                     |228        |3.672335824E8 |0                  |125465                      |0.0517        |0.50025         |432541                          |258228                               |
|7              |420583           |6.707077758477E10       |159470.97                 |0.06                      |1.0E7                     |272        |4.017901288E8 |0                  |114931                      |0.064672      |0.599054        |419640                          |277622                               |
|8              |449637           |7.003059850048E10       |155749.19                 |0.02                      |1.0E7                     |278        |3.5199401701E8|0                  |118684                      |0.061828      |0.502629        |441790                          |305162                               |
|9              |417919           |5.806776539842E10       |138945.02                 |0.0                       |1.0E7                     |255        |3.8457125476E8|1                  |98229                       |0.061017      |0.66228         |408456                          |310464                               |
|10             |392945           |6.519035217702E10       |165901.98                 |0.02                      |1.0E7                     |282        |3.7306069837E8|0                  |105648                      |0.071766      |0.572264        |393689                          |300173                               |
+---------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+-----------+--------------+-------------------+----------------------------+--------------+----------------+--------------------------------+-------------------------------------+
only showing top 10 rows

In [29]:
gold_hourly_fraud_summary_df = (
    silver_final_df
    .groupBy(
        "step",
        "transaction_day",
        "hour_of_day",
    )
    .agg(
        F.count("*").alias(
            "transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "total_transaction_amount"
        ),
        F.sum("is_fraud").alias(
            "fraud_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_count"
        ),
        F.sum(
            "is_high_value_transaction"
        ).alias(
            "high_value_transaction_count"
        ),
        F.countDistinct(
            "origin_account"
        ).alias(
            "unique_origin_accounts"
        ),
        F.countDistinct(
            "destination_account"
        ).alias(
            "unique_destination_accounts"
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.round(
            F.col("fraud_count")
            / F.col("transaction_count")
            * F.lit(100),
            6,
        ),
    )
    .withColumn(
        "flag_coverage_pct",
        F.when(
            F.col("fraud_count") > 0,
            F.round(
                F.col("flagged_fraud_count")
                / F.col("fraud_count")
                * F.lit(100),
                6,
            ),
        ).otherwise(F.lit(0.0)),
    )
    .orderBy(
        "step"
    )
)

In [30]:
gold_hourly_fraud_summary_df.show(n=10)

+----+---------------+-----------+-----------------+------------------------+-----------+-------------+-------------------+----------------------------+----------------------+---------------------------+--------------+-----------------+
|step|transaction_day|hour_of_day|transaction_count|total_transaction_amount|fraud_count| fraud_amount|flagged_fraud_count|high_value_transaction_count|unique_origin_accounts|unique_destination_accounts|fraud_rate_pct|flag_coverage_pct|
+----+---------------+-----------+-----------------+------------------------+-----------+-------------+-------------------+----------------------------+----------------------+---------------------------+--------------+-----------------+
|   1|              1|          0|             2708|          2.8542918115E8|         16|   3740247.01|                  0|                         451|                  2708|                       1633|      0.590842|              0.0|
|   2|              1|          1|             1014|           8.592160402E7|          8|   4186592.48|                  0|                         136|                  1014|                        754|      0.788955|              0.0|
|   3|              1|          2|              552|           4.329388442E7|          4|     66832.74|                  0|                          63|                   552|                        450|      0.724638|              0.0|
|   4|              1|          3|              565|           7.291002857E7|         10| 2.64002749E7|                  0|                          82|                   565|                        448|      1.769912|              0.0|
|   5|              1|          4|              665|           4.554808975E7|          6|    381841.54|                  0|                          72|                   665|                        566|      0.902256|              0.0|
|   6|              1|          5|             1660|          1.6431055122E8|         22|    974869.68|                  0|                         276|                  1660|                       1338|      1.325301|              0.0|
|   7|              1|          6|             6837|          8.3293081424E8|         12|1.241469406E7|                  0|                        1272|                  6837|                       5069|      0.175516|              0.0|
|   8|              1|          7|            21097|         3.43960240735E9|         12|   1589040.41|                  0|                        5184|                 21097|                      12589|       0.05688|              0.0|
|   9|              1|          8|            37628|         7.00837923943E9|         19|1.147663022E7|                  0|                       10653|                 37628|                      21831|      0.050494|              0.0|
|  10|              1|          9|            35991|         7.12421489371E9|         11|   6935977.72|                  0|                       10875|                 35991|                      23133|      0.030563|              0.0|
+----+---------------+-----------+-----------------+------------------------+-----------+-------------+-------------------+----------------------------+----------------------+---------------------------+--------------+-----------------+
only showing top 10 rows

In [31]:
gold_transaction_type_summary_df = (
    silver_final_df
    .groupBy(
        "transaction_type"
    )
    .agg(
        F.count("*").alias(
            "transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "total_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "average_amount"
        ),
        F.round(
            F.expr(
                "percentile_approx(amount, 0.5)"
            ),
            2,
        ).alias(
            "median_amount"
        ),
        F.round(
            F.min("amount"),
            2,
        ).alias(
            "minimum_amount"
        ),
        F.round(
            F.max("amount"),
            2,
        ).alias(
            "maximum_amount"
        ),
        F.sum("is_fraud").alias(
            "fraud_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_count"
        ),
        F.sum(
            "is_high_value_transaction"
        ).alias(
            "high_value_transaction_count"
        ),
    )
    .withColumn(
        "transaction_pct",
        F.round(
            F.col("transaction_count")
            / F.lit(silver_record_count)
            * F.lit(100),
            4,
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.round(
            F.col("fraud_count")
            / F.col("transaction_count")
            * F.lit(100),
            6,
        ),
    )
    .orderBy(
        F.desc("transaction_count")
    )
)

In [32]:
gold_transaction_type_summary_df.show(n=10, truncate=False)

+----------------+-----------------+------------------+--------------+-------------+--------------+--------------+-----------+---------------+-------------------+----------------------------+---------------+--------------+
|transaction_type|transaction_count|total_amount      |average_amount|median_amount|minimum_amount|maximum_amount|fraud_count|fraud_amount   |flagged_fraud_count|high_value_transaction_count|transaction_pct|fraud_rate_pct|
+----------------+-----------------+------------------+--------------+-------------+--------------+--------------+-----------+---------------+-------------------+----------------------------+---------------+--------------+
|CASH_OUT        |2237500          |3.9441299522449E11|176273.96     |147081.69    |0.0           |1.0E7         |4116       |5.98920224383E9|0                  |788559                      |35.1663        |0.183955      |
|PAYMENT         |2151495          |2.809337113837E10 |13057.6       |9482.36      |0.02          |238637.98     |0          |0.0            |0                  |6                           |33.8146        |0.0           |
|CASH_IN         |1399284          |2.3636739191246E11|168920.24     |143417.67    |0.04          |1915267.9     |0          |0.0            |0                  |475868                      |21.9923        |0.0           |
|TRANSFER        |532909           |4.8529198726317E11|910647.01     |486293.86    |2.6           |9.244551664E7 |4097       |6.06721318401E9|16                 |409110                      |8.3756         |0.768799      |
|DEBIT           |41432            |2.2719922128E8    |5483.67       |3048.69      |0.55          |569077.51     |0          |0.0            |0                  |27                          |0.6512         |0.0           |
+----------------+-----------------+------------------+--------------+-------------+--------------+--------------+-----------+---------------+-------------------+----------------------------+---------------+--------------+

In [33]:
gold_origin_account_summary_df = (
    silver_final_df
    .groupBy(
        "origin_account"
    )
    .agg(
        F.count("*").alias(
            "transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "total_transaction_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "average_transaction_amount"
        ),
        F.round(
            F.min("amount"),
            2,
        ).alias(
            "minimum_transaction_amount"
        ),
        F.round(
            F.max("amount"),
            2,
        ).alias(
            "maximum_transaction_amount"
        ),
        F.countDistinct(
            "destination_account"
        ).alias(
            "unique_destination_count"
        ),
        F.countDistinct(
            "transaction_type"
        ).alias(
            "unique_transaction_type_count"
        ),
        F.min("step").alias(
            "first_transaction_step"
        ),
        F.max("step").alias(
            "last_transaction_step"
        ),
        F.sum("is_fraud").alias(
            "fraud_transaction_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_transaction_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_count"
        ),
        F.sum(
            "is_high_value_transaction"
        ).alias(
            "high_value_transaction_count"
        ),
        F.sum(
            F.when(
                F.col("transaction_type") == "TRANSFER",
                1,
            ).otherwise(0)
        ).alias(
            "transfer_count"
        ),
        F.sum(
            F.when(
                F.col("transaction_type") == "CASH_OUT",
                1,
            ).otherwise(0)
        ).alias(
            "cash_out_count"
        ),
        F.sum(
            F.when(
                F.col("transaction_type") == "PAYMENT",
                1,
            ).otherwise(0)
        ).alias(
            "payment_count"
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.round(
            F.col("fraud_transaction_count")
            / F.col("transaction_count")
            * F.lit(100),
            6,
        ),
    )
)

In [34]:
gold_origin_account_summary_df.show(n=10)

+--------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+------------------------+-----------------------------+----------------------+---------------------+-----------------------+------------------------+-------------------+----------------------------+--------------+--------------+-------------+--------------+
|origin_account|transaction_count|total_transaction_amount|average_transaction_amount|minimum_transaction_amount|maximum_transaction_amount|unique_destination_count|unique_transaction_type_count|first_transaction_step|last_transaction_step|fraud_transaction_count|fraud_transaction_amount|flagged_fraud_count|high_value_transaction_count|transfer_count|cash_out_count|payment_count|fraud_rate_pct|
+--------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+------------------------+-----------------------------+----------------------+---------------------+-----------------------+------------------------+-------------------+----------------------------+--------------+--------------+-------------+--------------+
|   C1000169603|                1|                   169.1|                     169.1|                     169.1|                     169.1|                       1|                            1|                   140|                  140|                      0|                     0.0|                  0|                           0|             0|             0|            1|           0.0|
|   C1004875517|                1|                77199.73|                  77199.73|                  77199.73|                  77199.73|                       1|                            1|                   135|                  135|                      0|                     0.0|                  0|                           0|             0|             1|            0|           0.0|
|   C1006273572|                1|               207268.41|                 207268.41|                 207268.41|                 207268.41|                       1|                            1|                   138|                  138|                      0|                     0.0|                  0|                           1|             0|             1|            0|           0.0|
|   C1007956967|                1|                54348.02|                  54348.02|                  54348.02|                  54348.02|                       1|                            1|                    39|                   39|                      0|                     0.0|                  0|                           0|             0|             1|            0|           0.0|
|   C1009026399|                1|               137664.84|                 137664.84|                 137664.84|                 137664.84|                       1|                            1|                   154|                  154|                      0|                     0.0|                  0|                           0|             0|             1|            0|           0.0|
|   C1012998882|                1|                16339.33|                  16339.33|                  16339.33|                  16339.33|                       1|                            1|                    38|                   38|                      0|                     0.0|                  0|                           0|             0|             0|            1|           0.0|
|   C1015600350|                1|               748526.34|                 748526.34|                 748526.34|                 748526.34|                       1|                            1|                   155|                  155|                      0|                     0.0|                  0|                           1|             1|             0|            0|           0.0|
|   C1016328200|                1|                118359.9|                  118359.9|                  118359.9|                  118359.9|                       1|                            1|                   154|                  154|                      0|                     0.0|                  0|                           0|             0|             1|            0|           0.0|
|   C1016599939|                1|               276096.86|                 276096.86|                 276096.86|                 276096.86|                       1|                            1|                    18|                   18|                      0|                     0.0|                  0|                           1|             0|             1|            0|           0.0|
|   C1016869923|                1|                32095.96|                  32095.96|                  32095.96|                  32095.96|                       1|                            1|                   133|                  133|                      0|                     0.0|                  0|                           0|             0|             0|            1|           0.0|
+--------------+-----------------+------------------------+--------------------------+--------------------------+--------------------------+------------------------+-----------------------------+----------------------+---------------------+-----------------------+------------------------+-------------------+----------------------------+--------------+--------------+-------------+--------------+
only showing top 10 rows

In [35]:
gold_destination_account_summary_df = (
    silver_final_df
    .groupBy(
        "destination_account",
        "destination_category",
    )
    .agg(
        F.count("*").alias(
            "received_transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "received_total_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "received_average_amount"
        ),
        F.round(
            F.max("amount"),
            2,
        ).alias(
            "received_maximum_amount"
        ),
        F.countDistinct(
            "origin_account"
        ).alias(
            "unique_origin_count"
        ),
        F.min("step").alias(
            "first_received_step"
        ),
        F.max("step").alias(
            "last_received_step"
        ),
        F.sum("is_fraud").alias(
            "fraud_received_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_received_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_received_count"
        ),
        F.sum(
            "is_high_value_transaction"
        ).alias(
            "high_value_received_count"
        ),
    )
    .withColumn(
        "fraud_received_rate_pct",
        F.round(
            F.col("fraud_received_count")
            / F.col("received_transaction_count")
            * F.lit(100),
            6,
        ),
    )
)

In [36]:
gold_destination_account_summary_df.filter(
    F.col("fraud_received_count") > 0
).orderBy(
    F.desc("fraud_received_count"),
    F.desc("fraud_received_amount"),
).show(
    n=20,
    truncate=False,
)

+-------------------+--------------------+--------------------------+---------------------+-----------------------+-----------------------+-------------------+-------------------+------------------+--------------------+---------------------+----------------------------+-------------------------+-----------------------+
|destination_account|destination_category|received_transaction_count|received_total_amount|received_average_amount|received_maximum_amount|unique_origin_count|first_received_step|last_received_step|fraud_received_count|fraud_received_amount|flagged_fraud_received_count|high_value_received_count|fraud_received_rate_pct|
+-------------------+--------------------+--------------------------+---------------------+-----------------------+-----------------------+-------------------+-------------------+------------------+--------------------+---------------------+----------------------------+-------------------------+-----------------------+
|C668046170         |CUSTOMER            |5                         |1.096589685E7        |2193179.37             |1.0E7                  |5                  |269                |686               |2                   |1.016008868E7        |0                           |3                        |40.0                   |
|C1669818195        |CUSTOMER            |4                         |8983132.32           |2245783.08             |7782452.17             |4                  |446                |614               |2                   |8848239.99           |0                           |2                        |50.0                   |
|C1981613973        |CUSTOMER            |25                        |2.097165534E7        |838866.21              |8746777.31             |25                 |36                 |374               |2                   |7265501.67           |0                           |12                       |8.0                    |
|C1366192319        |CUSTOMER            |12                        |9126638.19           |760553.18              |4830219.15             |12                 |84                 |469               |2                   |7061799.65           |0                           |6                        |16.666667              |
|C964377943         |CUSTOMER            |4                         |6204778.23           |1551194.56             |5838803.23             |4                  |300                |401               |2                   |6014862.39           |0                           |1                        |50.0                   |
|C14138104          |CUSTOMER            |2                         |4597314.28           |2298657.14             |4135944.29             |2                  |415                |436               |2                   |4597314.28           |0                           |2                        |100.0                  |
|C1399829166        |CUSTOMER            |25                        |9831277.06           |393251.08              |2984434.36             |25                 |15                 |379               |2                   |3540009.28           |0                           |12                       |8.0                    |
|C643624257         |CUSTOMER            |17                        |5912357.32           |347785.72              |2374490.77             |17                 |134                |397               |2                   |3071716.97           |0                           |8                        |11.764706              |
|C1013511446        |CUSTOMER            |35                        |2.222617113E7        |635033.46              |2657484.81             |35                 |9                  |402               |2                   |2994972.2            |0                           |23                       |5.714286               |
|C1601170327        |CUSTOMER            |16                        |6549520.04           |409345.0               |2554662.97             |16                 |148                |380               |2                   |2842694.99           |0                           |9                        |12.5                   |
|C52390890          |CUSTOMER            |22                        |8375656.74           |380711.67              |2068118.36             |22                 |22                 |396               |2                   |2662695.58           |0                           |9                        |9.090909               |
|C104038589         |CUSTOMER            |23                        |6842787.53           |297512.5               |2050727.81             |23                 |39                 |587               |2                   |2202769.97           |0                           |11                       |8.695652               |
|C803116137         |CUSTOMER            |77                        |1.1915166225E8       |1547424.19             |3.375157704E7          |77                 |4                  |476               |2                   |1744765.69           |0                           |44                       |2.597403               |
|C904300960         |CUSTOMER            |32                        |1.130348245E7        |353233.83              |1975326.69             |32                 |6                  |326               |2                   |1427683.17           |0                           |17                       |6.25                   |
|C967226405         |CUSTOMER            |14                        |4967725.86           |354837.56              |855809.29              |14                 |162                |694               |2                   |1416085.46           |0                           |6                        |14.285714              |
|C385133759         |CUSTOMER            |18                        |5618285.07           |312126.95              |1664778.21             |18                 |34                 |688               |2                   |1396377.23           |0                           |8                        |11.111111              |
|C1259079602        |CUSTOMER            |9                         |3184910.42           |353878.94              |1058527.77             |9                  |44                 |589               |2                   |1214480.35           |0                           |4                        |22.222222              |
|C644163395         |CUSTOMER            |26                        |1.239464344E7        |476717.06              |2554755.63             |26                 |14                 |538               |2                   |1196176.06           |0                           |15                       |7.692308               |
|C1827800010        |CUSTOMER            |3                         |1320692.37           |440230.79              |1050635.77             |3                  |368                |724               |2                   |1140481.06           |0                           |1                        |66.666667              |
|C185805228         |CUSTOMER            |47                        |1.384706893E7        |294618.49              |2594904.29             |47                 |9                  |326               |2                   |1124385.07           |0                           |21                       |4.255319               |
+-------------------+--------------------+--------------------------+---------------------+-----------------------+-----------------------+-------------------+-------------------+------------------+--------------------+---------------------+----------------------------+-------------------------+-----------------------+
only showing top 20 rows

In [37]:
gold_high_value_summary_df = (
    silver_final_df
    .filter(
        F.col("is_high_value_transaction") == 1
    )
    .groupBy(
        "transaction_day",
        "transaction_type",
    )
    .agg(
        F.count("*").alias(
            "high_value_transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "high_value_total_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "high_value_average_amount"
        ),
        F.round(
            F.max("amount"),
            2,
        ).alias(
            "high_value_maximum_amount"
        ),
        F.sum("is_fraud").alias(
            "high_value_fraud_count"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "high_value_flagged_count"
        ),
    )
    .withColumn(
        "high_value_fraud_rate_pct",
        F.round(
            F.col("high_value_fraud_count")
            / F.col("high_value_transaction_count")
            * F.lit(100),
            6,
        ),
    )
    .orderBy(
        "transaction_day",
        "transaction_type",
    )
)

In [38]:
gold_high_value_summary_df.show(
    n=5,
    truncate=False,
)

+---------------+----------------+----------------------------+-----------------------+-------------------------+-------------------------+----------------------+------------------------+-------------------------+
|transaction_day|transaction_type|high_value_transaction_count|high_value_total_amount|high_value_average_amount|high_value_maximum_amount|high_value_fraud_count|high_value_flagged_count|high_value_fraud_rate_pct|
+---------------+----------------+----------------------------+-----------------------+-------------------------+-------------------------+----------------------+------------------------+-------------------------+
|1              |CASH_IN         |42946                       |1.358067710166E10      |316226.82                |1289407.91               |0                     |0                       |0.0                      |
|1              |CASH_OUT        |76731                       |2.522775263348E10      |328781.75                |1.0E7                    |65                    |0                       |0.084712                 |
|1              |TRANSFER        |36073                       |3.012066657812E10      |834992.0                 |1.0E7                    |62                    |0                       |0.171874                 |
|2              |CASH_IN         |33613                       |1.050648605166E10      |312572.1                 |1781905.26               |0                     |0                       |0.0                      |
|2              |CASH_OUT        |62131                       |2.026808172712E10      |326215.28                |1.0E7                    |99                    |0                       |0.159341                 |
+---------------+----------------+----------------------------+-----------------------+-------------------------+-------------------------+----------------------+------------------------+-------------------------+
only showing top 5 rows

In [39]:
gold_fraud_monitoring_df = (
    silver_final_df
    .filter(
        F.col("is_fraud") == 1
    )
    .select(
        "_record_hash",
        "step",
        "transaction_day",
        "hour_of_day",
        "transaction_type",
        "amount",
        "amount_category",
        "origin_account",
        "destination_account",
        "destination_category",
        "is_high_value_transaction",
        "is_flagged_fraud",
        "_pipeline_run_id",
        "_ingestion_timestamp",
        "_source_file",
    )
)

In [40]:
gold_fraud_monitoring_df.show(
    n=20,
    truncate=False,
)

+----------------------------------------------------------------+----+---------------+-----------+----------------+----------+---------------+--------------+-------------------+--------------------+-------------------------+----------------+------------------------------------+--------------------------+------------------------------------+
|_record_hash                                                    |step|transaction_day|hour_of_day|transaction_type|amount    |amount_category|origin_account|destination_account|destination_category|is_high_value_transaction|is_flagged_fraud|_pipeline_run_id                    |_ingestion_timestamp      |_source_file                        |
+----------------------------------------------------------------+----+---------------+-----------+----------------+----------+---------------+--------------+-------------------+--------------------+-------------------------+----------------+------------------------------------+--------------------------+------------------------------------+
|05b5efb9f4bdb7fb2b99e768a027cd215020ed36957d5047fbf32a12a3d168bc|1   |1              |0          |TRANSFER        |181.0     |LOW            |C1305486145   |C553264065         |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|bd0a1524a32e53ba0f5672f229a63a557c626ba90623afee4855beb9d435fdc3|1   |1              |0          |CASH_OUT        |181.0     |LOW            |C840083671    |C38997010          |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|1053f01df76422c021a5da5eeae77d708a98c3e9f3034a329a0ae9d5305823d1|1   |1              |0          |TRANSFER        |2806.0    |MEDIUM         |C1420196421   |C972765878         |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|9cc1e25fa020b2b83907fd1186b91eee9f85611478da113867a0e00220f56e8d|1   |1              |0          |CASH_OUT        |2806.0    |MEDIUM         |C2101527076   |C1007251739        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|ef17b47cd5584afd4824ab444d2080c977b6b6a4b146c20e386920356bc57907|1   |1              |0          |TRANSFER        |20128.0   |MEDIUM         |C137533655    |C1848415041        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|4cab90abcd95ded5e7402b6de0da2118434dba6003a436b309d4e528371a2a26|1   |1              |0          |CASH_OUT        |20128.0   |MEDIUM         |C1118430673   |C339924917         |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|e67a278a3e740a73d67f836d84bd2b927a90b369045da301ee5804034bb6bd57|1   |1              |0          |CASH_OUT        |416001.33 |VERY_HIGH      |C749981943    |C667346055         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|ca4eb814f767537fd13dbbc3cfe39c9a6c7cbaaab5de6aaa82250b7af32137e9|1   |1              |0          |TRANSFER        |1277212.77|VERY_HIGH      |C1334405552   |C431687661         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|d0bf8ca294d574e40645c05137f8b15056ece7235557facf2bcff6083fd8f712|1   |1              |0          |CASH_OUT        |1277212.77|VERY_HIGH      |C467632528    |C716083600         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|1cb3b17eb42ffeda097fa5abc1167cc261162a012602877f6d4497d46be403f4|1   |1              |0          |TRANSFER        |35063.63  |MEDIUM         |C1364127192   |C1136419747        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|4c8121910f3d1dc96ff0d9fea7d99a506324eccb3a60dfcb8e2e4fcbfd33e194|1   |1              |0          |CASH_OUT        |35063.63  |MEDIUM         |C1635772897   |C1983025922        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|147d081fb903f7e2ff13d527ffd82c30d00806097ceccc38b77077e1b9ccf247|1   |1              |0          |TRANSFER        |25071.46  |MEDIUM         |C669700766    |C1384210339        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|23dd04510a137cb79a76cfed6ab7ee4fe8a1934cde470e0d678ec67db17cae08|1   |1              |0          |CASH_OUT        |25071.46  |MEDIUM         |C1275464847   |C1364913072        |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|0b76072fd8e70c88c86870c771d9125f2130448e1771bf08aba7f056eb7292b7|1   |1              |0          |CASH_OUT        |132842.64 |HIGH           |C13692003     |C297927961         |CUSTOMER            |0                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|7453ae81a113fd36978c1660b79c85c2dac99928c3dda404d82e9cfcfebc1826|1   |1              |0          |TRANSFER        |235238.66 |VERY_HIGH      |C1872047468   |C116289363         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|15d8bf79c02957635968a7d610907832b16dd76452935d02f9496811a81b3f43|1   |1              |0          |CASH_OUT        |235238.66 |VERY_HIGH      |C1499825229   |C2100440237        |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|f1be0313714c14c752dc70b6db4cc09d27f4691ddc4b66e39fd38e6589c13f90|2   |1              |1          |TRANSFER        |1096187.24|VERY_HIGH      |C1093223281   |C2063275841        |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|00b6cf672382151e2b0da359c2a2a36d34d7fd0e1c1a4a607f3585e704b4bf76|2   |1              |1          |CASH_OUT        |1096187.24|VERY_HIGH      |C77163673     |C644345897         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|157ffe33bd5748357562fbbe86ac610b7610fb04317b09115ba56c79012396f0|2   |1              |1          |TRANSFER        |963532.14 |VERY_HIGH      |C1440057381   |C268086000         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
|ff7b703dbae5f4c2e72fa2ebe903dde0bc52f895d5305cca37c974acccd323c2|2   |1              |1          |CASH_OUT        |963532.14 |VERY_HIGH      |C430329518    |C991505714         |CUSTOMER            |1                        |0               |8be59cd7-9b19-4889-81c3-7adc20adbd19|2026-07-25 23:56:53.531152|PS_20174392719_1491204439457_log.csv|
+----------------------------------------------------------------+----+---------------+-----------+----------------+----------+---------------+--------------+-------------------+--------------------+-------------------------+----------------+------------------------------------+--------------------------+------------------------------------+
only showing top 20 rows

In [41]:
gold_fraud_record_count = (
    gold_fraud_monitoring_df.count()
)

print(
    "Fraud monitoring records:",
    f"{gold_fraud_record_count:,}",
)

Fraud monitoring records: 8,213

In [42]:
origin_history_window = (
    Window
    .partitionBy("origin_account")
    .orderBy(
        F.col("step"),
        F.col("_record_hash"),
    )
    .rowsBetween(
        Window.unboundedPreceding,
        -1,
    )
)

In [43]:
feature_enriched_df = (
    silver_final_df
    .withColumn(
        "prior_origin_transaction_count",
        F.count("*").over(
            origin_history_window
        ),
    )
    .withColumn(
        "prior_origin_total_amount",
        F.sum("amount").over(
            origin_history_window
        ),
    )
    .withColumn(
        "prior_origin_average_amount",
        F.avg("amount").over(
            origin_history_window
        ),
    )
    .withColumn(
        "prior_origin_maximum_amount",
        F.max("amount").over(
            origin_history_window
        ),
    )
    .withColumn(
        "prior_origin_fraud_count",
        F.sum("is_fraud").over(
            origin_history_window
        ),
    )
)

In [44]:
feature_enriched_df = (
    feature_enriched_df
    .fillna(
        {
            "prior_origin_transaction_count": 0,
            "prior_origin_total_amount": 0.0,
            "prior_origin_average_amount": 0.0,
            "prior_origin_maximum_amount": 0.0,
            "prior_origin_fraud_count": 0,
        }
    )
)

In [45]:
previous_transaction_window = (
    Window
    .partitionBy("origin_account")
    .orderBy(
        F.col("step"),
        F.col("_record_hash"),
    )
)

In [46]:
feature_enriched_df = (
    feature_enriched_df
    .withColumn(
        "previous_transaction_step",
        F.lag("step").over(
            previous_transaction_window
        ),
    )
    .withColumn(
        "previous_transaction_amount",
        F.lag("amount").over(
            previous_transaction_window
        ),
    )
    .withColumn(
        "steps_since_previous_transaction",
        F.col("step")
        - F.col("previous_transaction_step"),
    )
)

In [47]:
feature_enriched_df = (
    feature_enriched_df
    .fillna(
        {
            "previous_transaction_amount": 0.0,
            "steps_since_previous_transaction": -1,
        }
    )
)

In [48]:
feature_enriched_df = (
    feature_enriched_df
    .withColumn(
        "is_cash_in",
        (
            F.col("transaction_type") == "CASH_IN"
        ).cast("integer"),
    )
    .withColumn(
        "is_cash_out",
        (
            F.col("transaction_type") == "CASH_OUT"
        ).cast("integer"),
    )
    .withColumn(
        "is_debit",
        (
            F.col("transaction_type") == "DEBIT"
        ).cast("integer"),
    )
    .withColumn(
        "is_payment",
        (
            F.col("transaction_type") == "PAYMENT"
        ).cast("integer"),
    )
    .withColumn(
        "is_transfer",
        (
            F.col("transaction_type") == "TRANSFER"
        ).cast("integer"),
    )
)

In [49]:
gold_fraud_feature_df = (
    feature_enriched_df
    .select(
        "_record_hash",
        "step",
        "transaction_day",
        "hour_of_day",
        "transaction_type",
        "amount",
        "amount_category",
        "origin_account",
        "destination_account",
        "destination_category",
        "is_customer_destination",
        "is_merchant_destination",
        "is_high_value_transaction",
        "is_cash_in",
        "is_cash_out",
        "is_debit",
        "is_payment",
        "is_transfer",
        "prior_origin_transaction_count",
        F.round(
            "prior_origin_total_amount",
            2,
        ).alias(
            "prior_origin_total_amount"
        ),
        F.round(
            "prior_origin_average_amount",
            2,
        ).alias(
            "prior_origin_average_amount"
        ),
        F.round(
            "prior_origin_maximum_amount",
            2,
        ).alias(
            "prior_origin_maximum_amount"
        ),
        "prior_origin_fraud_count",
        "previous_transaction_step",
        "previous_transaction_amount",
        "steps_since_previous_transaction",
        "is_flagged_fraud",
        "is_fraud",
        "_pipeline_run_id",
        "_ingestion_timestamp",
        "_source_file",
    )
)

In [50]:
prohibited_balance_columns = {
    "old_balance_origin",
    "new_balance_origin",
    "old_balance_destination",
    "new_balance_destination",
}

feature_columns = set(
    gold_fraud_feature_df.columns
)

unexpected_balance_columns = (
    feature_columns
    & prohibited_balance_columns
)

print(
    "Balance columns found in feature table:",
    unexpected_balance_columns,
)

Balance columns found in feature table: set()

In [51]:
assert not unexpected_balance_columns, (
    "Balance fields must not be included "
    "in the fraud feature table."
)

print(
    "Balance-field exclusion validation passed."
)

Balance-field exclusion validation passed.

In [52]:
gold_fraud_feature_df.select(
    "_record_hash",
    "step",
    "transaction_type",
    "amount",
    "is_high_value_transaction",
    "prior_origin_transaction_count",
    "prior_origin_average_amount",
    "previous_transaction_amount",
    "steps_since_previous_transaction",
    "is_fraud",
).show(
    n=20,
    truncate=False,
)

+----------------------------------------------------------------+----+----------------+---------+-------------------------+------------------------------+---------------------------+---------------------------+--------------------------------+--------+
|_record_hash                                                    |step|transaction_type|amount   |is_high_value_transaction|prior_origin_transaction_count|prior_origin_average_amount|previous_transaction_amount|steps_since_previous_transaction|is_fraud|
+----------------------------------------------------------------+----+----------------+---------+-------------------------+------------------------------+---------------------------+---------------------------+--------------------------------+--------+
|8a11360320e80d55872d167e9d8eb93d60bc73870a772f324c248fd1cf869508|254 |CASH_IN         |49360.77 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|ff315466b781454d265816e6239301ea887a493df82ca3e16f23385a01c5ca6a|210 |CASH_OUT        |239387.4 |1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|bb5420f88eb29916cd6e3014f6bd2bf9ff85dd5e0fb5d6b711e773c3ad3b5f9d|156 |CASH_IN         |108365.47|0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|59834be845122a9bb4de97dc3e44f26d6a4f4e13a506c77d00eda6aeedd447d0|283 |PAYMENT         |17206.98 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|63f14409929efd9b153177a0547ee8a8a8924d29f3f4c552712a974d927490ce|402 |CASH_OUT        |234442.89|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|da163a8903cc77bb7dbd34619d49319499758b9175632294ec4626122d93ec74|403 |TRANSFER        |127894.89|0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|e0823c98a90f05145485cce6a041fe4948b680197399d54cc8ffc5ca0422a268|213 |CASH_OUT        |33414.36 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|4491f3e16ac704888b6f295f980a993a8a5699d765b5c861a0befad1f35df0c1|274 |PAYMENT         |4373.25  |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|99122b5777eac16d79ef78c3d933897427f1c67ed098163637a8b9b66e03c307|262 |PAYMENT         |11029.74 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|28cb4c7ea31a93b6cde45e40a89f5fd65fc578d9281944c8d7cfad295f17513d|544 |PAYMENT         |15678.95 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|5801c2cf8d828da082fe87dafd627b6407f564a495035b723c92eaa1f957d3ad|155 |CASH_OUT        |245438.01|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|27898fe73e39891836c246e9e611478673d6fbb7be399767756123a8737eee27|353 |CASH_IN         |71801.78 |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|309f10a22fc258e8c50851274a2b23e0e7882d0e8d687ee8265173f28b1c2762|404 |CASH_OUT        |382033.65|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|10fba538e57ae6a07adac2d0017216af5cf97566039856b7139b0dde657d947a|258 |PAYMENT         |1140.86  |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|10e0056d06e4742dd9e6be7648a03e8d6ec055d13ca9068fbd4525cc1314f923|402 |CASH_OUT        |159128.23|0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|4d533e21a73f153434537084e66b521d63b19c3e63632acd16ec190808ac979f|208 |TRANSFER        |611835.47|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|2644c126adf7956b864d5b8a495bbb9475fded0fb36bac8fc0b369b15dffebd5|259 |PAYMENT         |1313.16  |0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|143b4103d051651033bb0d1d7691d14936cca5296824829b43601f5797750921|309 |CASH_OUT        |412480.14|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
|c623df07b23df4be467a45ee69e1bffba220890a2ab3394cd8c5c43c3d5ae03e|153 |TRANSFER        |150384.96|0                        |0                             |0.0                        |0.0                        |-1                              |0       |
|afab9f140dde377a4ae8f042926b7b31847563ca56d79e8be0bbaeccbf01cc32|192 |TRANSFER        |343768.66|1                        |0                             |0.0                        |0.0                        |-1                              |0       |
+----------------------------------------------------------------+----+----------------+---------+-------------------------+------------------------------+---------------------------+---------------------------+--------------------------------+--------+
only showing top 20 rows

In [53]:
type_summary_record_total = (
    gold_transaction_type_summary_df
    .agg(
        F.sum(
            "transaction_count"
        ).alias("record_count")
    )
    .first()["record_count"]
)

print(
    "Silver records:",
    f"{silver_record_count:,}",
)

print(
    "Transaction-type Gold total:",
    f"{type_summary_record_total:,}",
)

Silver records: 6,362,620
Transaction-type Gold total: 6,362,620

In [54]:
assert (
    silver_record_count
    == type_summary_record_total
)

print(
    "Transaction-type reconciliation passed."
)

Transaction-type reconciliation passed.

In [55]:
daily_summary_record_total = (
    gold_daily_transaction_summary_df
    .agg(
        F.sum(
            "transaction_count"
        ).alias("record_count")
    )
    .first()["record_count"]
)

assert (
    silver_record_count
    == daily_summary_record_total
)

print(
    "Daily-summary reconciliation passed."
)

Daily-summary reconciliation passed.

In [56]:
hourly_summary_record_total = (
    gold_hourly_fraud_summary_df
    .agg(
        F.sum(
            "transaction_count"
        ).alias("record_count")
    )
    .first()["record_count"]
)

assert (
    silver_record_count
    == hourly_summary_record_total
)

print(
    "Hourly-summary reconciliation passed."
)

Hourly-summary reconciliation passed.

In [57]:
silver_fraud_count = (
    silver_final_df
    .agg(
        F.sum("is_fraud").alias(
            "fraud_count"
        )
    )
    .first()["fraud_count"]
)

gold_fraud_count = (
    gold_fraud_monitoring_df.count()
)

print(
    "Silver fraud count:",
    f"{silver_fraud_count:,}",
)

print(
    "Gold fraud-monitoring count:",
    f"{gold_fraud_count:,}",
)

Silver fraud count: 8,213
Gold fraud-monitoring count: 8,213

In [58]:
assert (
    silver_fraud_count
    == gold_fraud_count
)

print(
    "Fraud-monitoring reconciliation passed."
)

Fraud-monitoring reconciliation passed.

In [59]:
feature_table_count = (
    gold_fraud_feature_df.count()
)

print(
    "Silver count:",
    f"{silver_record_count:,}",
)

print(
    "Feature table count:",
    f"{feature_table_count:,}",
)

Silver count: 6,362,620
Feature table count: 6,362,620

In [60]:
assert (
    silver_record_count
    == feature_table_count
)

print(
    "Fraud-feature count reconciliation passed."
)

Fraud-feature count reconciliation passed.

In [61]:
gold_daily_transaction_summary_df.createOrReplaceTempView(
    "gold_daily_transaction_summary"
)

gold_hourly_fraud_summary_df.createOrReplaceTempView(
    "gold_hourly_fraud_summary"
)

gold_transaction_type_summary_df.createOrReplaceTempView(
    "gold_transaction_type_summary"
)

gold_origin_account_summary_df.createOrReplaceTempView(
    "gold_origin_account_summary"
)

gold_destination_account_summary_df.createOrReplaceTempView(
    "gold_destination_account_summary"
)

gold_fraud_monitoring_df.createOrReplaceTempView(
    "gold_fraud_monitoring"
)

gold_fraud_feature_df.createOrReplaceTempView(
    "gold_fraud_features"
)

In [62]:
spark.sql(
    """
    SELECT
        transaction_type,
        transaction_count,
        total_amount,
        fraud_count,
        fraud_amount,
        fraud_rate_pct
    FROM gold_transaction_type_summary
    ORDER BY fraud_rate_pct DESC
    """
).show(
    truncate=False
)

+----------------+-----------------+------------------+-----------+---------------+--------------+
|transaction_type|transaction_count|total_amount      |fraud_count|fraud_amount   |fraud_rate_pct|
+----------------+-----------------+------------------+-----------+---------------+--------------+
|TRANSFER        |532909           |4.8529198726317E11|4097       |6.06721318401E9|0.768799      |
|CASH_OUT        |2237500          |3.9441299522449E11|4116       |5.98920224383E9|0.183955      |
|DEBIT           |41432            |2.2719922128E8    |0          |0.0            |0.0           |
|CASH_IN         |1399284          |2.3636739191246E11|0          |0.0            |0.0           |
|PAYMENT         |2151495          |2.809337113837E10 |0          |0.0            |0.0           |
+----------------+-----------------+------------------+-----------+---------------+--------------+

In [63]:
gold_daily_type_summary_df = (
    silver_final_df
    .groupBy(
        "transaction_day",
        "transaction_type",
    )
    .agg(
        F.count("*").alias(
            "transaction_count"
        ),
        F.round(
            F.sum("amount"),
            2,
        ).alias(
            "total_amount"
        ),
        F.round(
            F.avg("amount"),
            2,
        ).alias(
            "average_amount"
        ),
        F.sum("is_fraud").alias(
            "fraud_count"
        ),
        F.round(
            F.sum(
                F.when(
                    F.col("is_fraud") == 1,
                    F.col("amount"),
                ).otherwise(0)
            ),
            2,
        ).alias(
            "fraud_amount"
        ),
        F.sum(
            "is_flagged_fraud"
        ).alias(
            "flagged_fraud_count"
        ),
    )
    .withColumn(
        "fraud_rate_pct",
        F.round(
            F.col("fraud_count")
            / F.col("transaction_count")
            * F.lit(100),
            6,
        ),
    )
    .orderBy(
        "transaction_day",
        "transaction_type",
    )
)
gold_daily_type_summary_df.show(
    n=30,
    truncate=False,
)

+---------------+----------------+-----------------+-----------------+--------------+-----------+--------------+-------------------+--------------+
|transaction_day|transaction_type|transaction_count|total_amount     |average_amount|fraud_count|fraud_amount  |flagged_fraud_count|fraud_rate_pct|
+---------------+----------------+-----------------+-----------------+--------------+-----------+--------------+-------------------+--------------+
|1              |CASH_IN         |124026           |2.12381194331E10 |171239.25     |0          |0.0           |0                  |0.0           |
|1              |CASH_OUT        |204397           |3.749451502343E10|183439.65     |141        |1.05052284E8  |0                  |0.068983      |
|1              |DEBIT           |4470             |2.79225835E7     |6246.66       |0          |0.0           |0                  |0.0           |
|1              |PAYMENT         |194676           |2.19243002602E9  |11261.94      |0          |0.0           |0                  |0.0           |
|1              |TRANSFER        |46686            |3.11788785596E10 |667842.15     |130        |1.0611154346E8|0                  |0.278456      |
|2              |CASH_IN         |99707            |1.681582953536E10|168652.45     |0          |0.0           |0                  |0.0           |
|2              |CASH_OUT        |164605           |3.017427358315E10|183313.23     |156        |1.8954221263E8|0                  |0.094772      |
|2              |DEBIT           |2510             |1.266401928E7    |5045.43       |0          |0.0           |0                  |0.0           |
|2              |PAYMENT         |150147           |1.66109317318E9  |11063.11      |0          |0.0           |0                  |0.0           |
|2              |TRANSFER        |38269            |2.257478208619E10|589897.36     |153        |1.8969747244E8|0                  |0.399801      |
|3              |CASH_IN         |137              |2.370517678E7    |173030.49     |0          |0.0           |0                  |0.0           |
|3              |CASH_OUT        |240              |2.1020880175E8   |875870.01     |155        |1.972544303E8 |0                  |64.583333     |
|3              |DEBIT           |24               |31606.65         |1316.94       |0          |0.0           |0                  |0.0           |
|3              |PAYMENT         |480              |3127637.43       |6515.91       |0          |0.0           |0                  |0.0           |
|3              |TRANSFER        |189              |2.1001125002E8   |1111170.64    |155        |1.972544303E8 |0                  |82.010582     |
|4              |CASH_IN         |4848             |7.8429426202E8   |161776.87     |0          |0.0           |0                  |0.0           |
|4              |CASH_OUT        |6252             |1.26622602429E9  |202531.35     |131        |2.1912340801E8|0                  |2.095329      |
|4              |DEBIT           |340              |2031923.85       |5976.25       |0          |0.0           |0                  |0.0           |
|4              |PAYMENT         |14286            |1.2611784007E8   |8828.07       |0          |0.0           |0                  |0.0           |
|4              |TRANSFER        |2514             |1.65187731036E9  |657071.32     |131        |2.1912340801E8|0                  |5.210819      |
|5              |CASH_IN         |1450             |2.4217877221E8   |167019.84     |0          |0.0           |0                  |0.0           |
|5              |CASH_OUT        |1769             |4.2161259309E8   |238333.86     |126        |1.2249028906E8|0                  |7.122668      |
|5              |DEBIT           |194              |933730.72        |4813.04       |0          |0.0           |0                  |0.0           |
|5              |PAYMENT         |5470             |4.981613816E7    |9107.16       |0          |0.0           |0                  |0.0           |
|5              |TRANSFER        |906              |6.1059260487E8   |673943.27     |126        |1.2249028906E8|0                  |13.907285     |
|6              |CASH_IN         |99972            |1.737984461076E10|173847.12     |0          |0.0           |0                  |0.0           |
|6              |CASH_OUT        |159596           |2.99625529285E10 |187740.0      |114        |1.836167912E8 |0                  |0.07143       |
|6              |DEBIT           |2663             |1.238502787E7    |4650.78       |0          |0.0           |0                  |0.0           |
|6              |PAYMENT         |142460           |2.0214749758E9   |14189.77      |0          |0.0           |0                  |0.0           |
|6              |TRANSFER        |36314            |2.403372882541E10|661830.94     |114        |1.836167912E8 |0                  |0.313929      |
+---------------+----------------+-----------------+-----------------+--------------+-----------+--------------+-------------------+--------------+
only showing top 30 rows

In [64]:
daily_summary_pdf = (
    gold_daily_transaction_summary_df
    .toPandas()
)

daily_type_summary_pdf = (
    gold_daily_type_summary_df
    .toPandas()
)

hourly_fraud_summary_pdf = (
    gold_hourly_fraud_summary_df
    .toPandas()
)

transaction_type_summary_pdf = (
    gold_transaction_type_summary_df
    .toPandas()
)

high_value_summary_pdf = (
    gold_high_value_summary_df
    .toPandas()
)

c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()
c:\Projects\paysim-financial-data-pipeline\.venv\Lib\site-packages\pyspark\sql\pandas\conversion.py:298: FutureWarning: PySpark does not yet fully support pandas >= 3.0.0. Some features may not work correctly. It is recommended to use pandas < 3.0.0 for now.
  require_minimum_pandas_version()

In [65]:
daily_summary_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / f"daily_transaction_summary_{pipeline_run_id}.csv"
)

daily_type_summary_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / f"daily_type_summary_{pipeline_run_id}.csv"
)

hourly_summary_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / f"hourly_fraud_summary_{pipeline_run_id}.csv"
)

transaction_type_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / f"transaction_type_summary_{pipeline_run_id}.csv"
)

high_value_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / f"high_value_summary_{pipeline_run_id}.csv"
)

In [66]:
daily_summary_pdf.to_csv(
    daily_summary_file,
    index=False,
)

daily_type_summary_pdf.to_csv(
    daily_type_summary_file,
    index=False,
)

hourly_fraud_summary_pdf.to_csv(
    hourly_summary_file,
    index=False,
)

transaction_type_summary_pdf.to_csv(
    transaction_type_file,
    index=False,
)

high_value_summary_pdf.to_csv(
    high_value_file,
    index=False,
)

In [67]:
print("Daily summary:", daily_summary_file)
print("Daily type summary:", daily_type_summary_file)
print("Hourly summary:", hourly_summary_file)
print("Transaction type summary:", transaction_type_file)
print("High-value summary:", high_value_file)

Daily summary: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\daily_transaction_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv
Daily type summary: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\daily_type_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv
Hourly summary: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\hourly_fraud_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv
Transaction type summary: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\transaction_type_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv
High-value summary: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\high_value_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv

In [68]:
gold_table_registry = [
    {
        "table_name": "gold_daily_transaction_summary",
        "grain": "one row per transaction day",
        "purpose": "Daily transaction and fraud monitoring",
        "expected_size": "small",
    },
    {
        "table_name": "gold_daily_type_summary",
        "grain": "one row per day and transaction type",
        "purpose": "Daily transaction-type analytics",
        "expected_size": "small",
    },
    {
        "table_name": "gold_hourly_fraud_summary",
        "grain": "one row per PaySim step",
        "purpose": "Hourly fraud monitoring",
        "expected_size": "small",
    },
    {
        "table_name": "gold_transaction_type_summary",
        "grain": "one row per transaction type",
        "purpose": "Transaction-type performance",
        "expected_size": "very small",
    },
    {
        "table_name": "gold_origin_account_summary",
        "grain": "one row per origin account",
        "purpose": "Origin-customer activity analysis",
        "expected_size": "large",
    },
    {
        "table_name": "gold_destination_account_summary",
        "grain": "one row per destination account",
        "purpose": "Destination-account activity analysis",
        "expected_size": "large",
    },
    {
        "table_name": "gold_high_value_summary",
        "grain": "one row per day and transaction type",
        "purpose": "High-value transaction monitoring",
        "expected_size": "small",
    },
    {
        "table_name": "gold_fraud_monitoring",
        "grain": "one row per fraudulent transaction",
        "purpose": "Detailed fraud investigation",
        "expected_size": "medium",
    },
    {
        "table_name": "gold_fraud_features",
        "grain": "one row per transaction",
        "purpose": "Fraud analytics and model input",
        "expected_size": "large",
    },
]

In [69]:
gold_table_registry_pdf = pd.DataFrame(
    gold_table_registry
)

gold_table_registry_pdf

,table_name,grain,purpose,expected_size
0,gold_daily_transaction_summary,one row per transaction day,Daily transaction and fraud monitoring,small
1,gold_daily_type_summary,one row per day and transaction type,Daily transaction-type analytics,small
2,gold_hourly_fraud_summary,one row per PaySim step,Hourly fraud monitoring,small
3,gold_transaction_type_summary,one row per transaction type,Transaction-type performance,very small
4,gold_origin_account_summary,one row per origin account,Origin-customer activity analysis,large
5,gold_destination_account_summary,one row per destination account,Destination-account activity analysis,large
6,gold_high_value_summary,one row per day and transaction type,High-value transaction monitoring,small
7,gold_fraud_monitoring,one row per fraudulent transaction,Detailed fraud investigation,medium
8,gold_fraud_features,one row per transaction,Fraud analytics and model input,large

In [70]:
gold_registry_file = (
    GOLD_SUMMARY_OUTPUT_PATH
    / "gold_table_registry.csv"
)

gold_table_registry_pdf.to_csv(
    gold_registry_file,
    index=False,
)

print(
    "Gold registry written to:",
    gold_registry_file,
)

Gold registry written to: C:\Projects\paysim-financial-data-pipeline\data\gold\summary_exports\gold_table_registry.csv

In [71]:
daily_row_count = (
    gold_daily_transaction_summary_df.count()
)

daily_type_row_count = (
    gold_daily_type_summary_df.count()
)

hourly_row_count = (
    gold_hourly_fraud_summary_df.count()
)

type_summary_row_count = (
    gold_transaction_type_summary_df.count()
)

origin_summary_row_count = (
    gold_origin_account_summary_df.count()
)

destination_summary_row_count = (
    gold_destination_account_summary_df.count()
)

high_value_summary_row_count = (
    gold_high_value_summary_df.count()
)

fraud_monitoring_row_count = (
    gold_fraud_monitoring_df.count()
)

In [72]:
print(daily_row_count)
print(daily_type_row_count)
print(hourly_row_count)
print(type_summary_row_count)
print(origin_summary_row_count)
print(destination_summary_row_count)
print(high_value_summary_row_count)
print(fraud_monitoring_row_count)

31
152
743
5
6353307
2722362
103
8213

In [73]:
pipeline_end_timestamp = datetime.now(
    timezone.utc
)

duration_seconds = (
    pipeline_end_timestamp
    - pipeline_start_timestamp
).total_seconds()

In [74]:
audit_record = {
    "pipeline_run_id": pipeline_run_id,
    "pipeline_name": "paysim_silver_to_gold",
    "source_file": source_filename,
    "pipeline_start_timestamp": (
        pipeline_start_timestamp.isoformat()
    ),
    "pipeline_end_timestamp": (
        pipeline_end_timestamp.isoformat()
    ),
    "duration_seconds": duration_seconds,
    "silver_record_count": silver_record_count,
    "daily_summary_row_count": daily_row_count,
    "daily_type_summary_row_count": daily_type_row_count,
    "hourly_summary_row_count": hourly_row_count,
    "transaction_type_summary_row_count": (
        type_summary_row_count
    ),
    "origin_account_summary_row_count": (
        origin_summary_row_count
    ),
    "destination_account_summary_row_count": (
        destination_summary_row_count
    ),
    "high_value_summary_row_count": (
        high_value_summary_row_count
    ),
    "fraud_monitoring_row_count": (
        fraud_monitoring_row_count
    ),
    "fraud_feature_row_count": (
        feature_table_count
    ),
    "daily_reconciliation_passed": (
        silver_record_count
        == daily_summary_record_total
    ),
    "hourly_reconciliation_passed": (
        silver_record_count
        == hourly_summary_record_total
    ),
    "type_reconciliation_passed": (
        silver_record_count
        == type_summary_record_total
    ),
    "fraud_reconciliation_passed": (
        silver_fraud_count
        == gold_fraud_count
    ),
    "pipeline_status": "SUCCESS",
}

In [75]:
audit_pdf = pd.DataFrame(
    [audit_record]
)

audit_pdf.T

                                                                          0
pipeline_run_id                        8be59cd7-9b19-4889-81c3-7adc20adbd19
pipeline_name                                         paysim_silver_to_gold
source_file                            PS_20174392719_1491204439457_log.csv
pipeline_start_timestamp                   2026-07-25T23:56:41.365225+00:00
pipeline_end_timestamp                     2026-07-25T23:59:25.923660+00:00
duration_seconds                                                 164.558435
silver_record_count                                                 6362620
daily_summary_row_count                                                  31
daily_type_summary_row_count                                            152
hourly_summary_row_count                                                743
transaction_type_summary_row_count                                        5
origin_account_summary_row_count                                    6353307
destination_account_summary_row_count                               2722362
high_value_summary_row_count                                            103
fraud_monitoring_row_count                                             8213
fraud_feature_row_count                                             6362620
daily_reconciliation_passed                                            True
hourly_reconciliation_passed                                           True
type_reconciliation_passed                                             True
fraud_reconciliation_passed                                            True
pipeline_status                                                     SUCCESS

In [76]:
audit_file_path = (
    AUDIT_OUTPUT_PATH
    / f"silver_to_gold_audit_{pipeline_run_id}.csv"
)

audit_pdf.to_csv(
    audit_file_path,
    index=False,
)

print(
    "Gold audit written to:",
    audit_file_path,
)

Gold audit written to: C:\Projects\paysim-financial-data-pipeline\data\gold\pipeline_audit\silver_to_gold_audit_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv

## Final Findings

### Gold tables created

The Silver transaction dataset was transformed into multiple analytics-ready
Gold tables:

- daily transaction summary;
- daily transaction-type summary;
- hourly fraud summary;
- transaction-type summary;
- origin-account activity summary;
- destination-account activity summary;
- high-value transaction summary;
- fraud-monitoring table;
- fraud feature table.

### Business value

The Gold layer supports:

- daily and hourly transaction monitoring;
- fraud trend analysis;
- high-value transfer monitoring;
- account-level activity profiling;
- transaction-type performance reporting;
- dashboard development;
- SQL reporting;
- downstream machine-learning workflows.

### Reconciliation

- Daily Gold transaction totals matched Silver.
- Hourly Gold transaction totals matched Silver.
- Transaction-type Gold totals matched Silver.
- Fraud-monitoring records matched the Silver fraud count.
- The fraud feature table preserved one row per valid Silver transaction.

### Feature-table design

- Balance columns were intentionally excluded.
- Historical account features were computed using Spark window functions.
- Transaction-type indicators were created.
- Previous-transaction features were derived.
- The label `is_fraud` was retained for downstream supervised learning.

### Persistence

Small Gold summaries were exported to CSV using Pandas.

Large Gold tables remain Spark DataFrames because native Windows Spark Parquet
persistence is currently deferred. These tables will later be written through
WSL2, Docker, or another Linux-compatible Spark environment.

## Engineering Decisions

1. Gold tables have clearly defined grains.

2. Each table serves a specific analytical consumer.

3. Aggregate tables are reconciled against the Silver source.

4. Detailed fraud records remain separate from aggregate monitoring tables.

5. The fraud feature table excludes balance columns to avoid documented target
   leakage.

6. Window functions use only prior origin-account records where possible.

7. Small Gold outputs may be exported through Pandas.

8. Large Gold datasets must remain in Spark and should later be persisted as
   Parquet or loaded into PostgreSQL.

9. Account-level Gold tables are not converted to Pandas because of their high
   cardinality.

10. Pipeline audit records document row counts, execution time, and
    reconciliation status.

In [77]:
sorted(
    path.name
    for path in GOLD_SUMMARY_OUTPUT_PATH.iterdir()
)

['daily_transaction_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv',
 'daily_type_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv',
 'gold_table_registry.csv',
 'high_value_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv',
 'hourly_fraud_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv',
 'transaction_type_summary_8be59cd7-9b19-4889-81c3-7adc20adbd19.csv']

In [78]:
silver_final_df.unpersist()

print("Silver DataFrame cache released.")

Silver DataFrame cache released.

In [79]:
spark.stop()

print("Spark session stopped.")

Spark session stopped.